name: flutter_todo_project6_supabase
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  supabase_flutter: ^1.10.25

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: DancingScript
      fonts:
        - asset: fonts\DancingScript-Regular.ttf
          weight: 400
        - asset: fonts\DancingScript-Bold.ttf
          weight: 700
        - asset: fonts\DancingScript-Medium.ttf
          weight: 500
        - asset: fonts\DancingScript-SemiBold.ttf
          weight: 600

    - family: Merienda
      fonts:
        - asset: fonts\Merienda-Regular.ttf
          weight: 400
        - asset: fonts\Merienda-Light.ttf
          weight: 300
        - asset: fonts\Merienda-Bold.ttf
          weight: 700
        - asset: fonts\Merienda-Medium.ttf
          weight: 500
        - asset: fonts\Merienda-SemiBold.ttf
          weight: 600

  assets:
    - assets/
